export const titles = [
    'Average Product Price by Brand',
    'Brand Sales by Month',
    'Brand Sales by Year',
    // 'Brand Sales by Part of Year',
    'Costs by Month',
    'Costs by Year',
    'Company Shoe Deliveries',
    'Discount Losses by Month',
    'Discount Losses by Year',
    'Profit by Month',
    'Profit by Year',
    'Profit by Season',
    'Top 5 Active Customers',
    'Top 5 Popular Products',
    // new
    'Costs By Part Of Year',
    'Discount Losses By Part Of Year',
    'Income By Year And Seasons',
    'Income By Every Month',
    'Income By Year',
    'Job Title And Salary',
    'New Customers By Month In Year',
    'New Customers By Year',
    'New Customers By Season',
    'Employee Orders By Month In Year',
    'Employee Orders By Seasons',
    'Employee Orders By All Years',
    'Pairs By Price Range',
    'Purchased Shoe Sizes',
    'Sales Percentage By Material',
    'Shoe Type Percentage',
    'Shoe Type Percentage By Brand',
    'Shoe Type Percentage By Company',
    'Customers By Sex',
    'Monthly Sales By Sex',
    'Supplier Pairs Percentage',
    'Shoe Type Sales By Year',
    'Shoe Type Sales By Month',
    'Shoe Type Sales By Season',
    'Customers Sex M',
    'Customers Sex W'
]
